// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    capability_ranked: {
        name: "capability_ranked";
        parameters: {
          /** STRING - use sql.string() */
          capability: SQLStringMarker;
          /** STRING - use sql.string() */
          state: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          unique_id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          facility_type: string;
          /** @sqlType STRING */
          district_norm: string;
          /** @sqlType STRING */
          state_name: string;
          /** @sqlType STRING */
          tier: string;
          /** @sqlType INT */
          score: number;
          /** @sqlType INT */
          n_source_urls: number;
          /** @sqlType DOUBLE */
          need_score: number;
        }>;
      };
    facility_detail: {
        name: "facility_detail";
        parameters: {
          /** STRING - use sql.string() */
          unique_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          capability: string;
          /** @sqlType STRING */
          tier: string;
          /** @sqlType STRING */
          explanation: string;
          /** @sqlType STRING */
          evidence_json: string;
          /** @sqlType STRING */
          citation_urls_json: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          facility_type: string;
          /** @sqlType STRING */
          district_norm: string;
          /** @sqlType STRING */
          state_name: string;
          /** @sqlType INT */
          num_doctors: number;
          /** @sqlType INT */
          capacity_beds: number;
          /** @sqlType STRING */
          specialties_json: string;
          /** @sqlType STRING */
          capabilities_json: string;
          /** @sqlType STRING */
          equipment_json: string;
        }>;
      };
    states: {
        name: "states";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          state_name: string;
        }>;
      };
  }
}
