-- Silver: prompt-ready, auditable inputs for LLM review of each facility x capability pair.
-- This does NOT change the deterministic trust tier. It packages the same evidence into a
-- stable serving table so model inference can be run offline and written back separately.
CREATE OR REPLACE TABLE virtue_foundation_dataset_cleaned.silver.facility_capability_llm_inputs AS
SELECT
  a.unique_id,
  a.capability,
  a.name,
  a.facility_type,
  a.operator_type,
  a.district_norm,
  a.state_name,
  g.address_city,
  g.pincode,
  a.latitude,
  a.longitude,
  f.num_doctors,
  f.capacity_beds,
  f.source_content_id,
  current_timestamp() AS input_snapshot_ts,
  sha2(concat_ws('||',
    coalesce(a.unique_id, ''),
    coalesce(a.capability, ''),
    coalesce(a.name, ''),
    coalesce(a.facility_type, ''),
    coalesce(a.operator_type, ''),
    coalesce(a.district_norm, ''),
    coalesce(a.state_name, ''),
    coalesce(g.address_city, ''),
    coalesce(cast(g.pincode AS string), ''),
    coalesce(cast(a.latitude AS string), ''),
    coalesce(cast(a.longitude AS string), ''),
    coalesce(f.capability, ''),
    coalesce(f.specialties, ''),
    coalesce(f.procedure, ''),
    coalesce(f.equipment, ''),
    coalesce(f.description, ''),
    coalesce(a.tier, ''),
    coalesce(cast(a.score AS string), ''),
    coalesce(a.explanation, ''),
    coalesce(cast(a.structured_hit AS string), ''),
    coalesce(cast(a.claim_hit AS string), ''),
    coalesce(cast(a.prose_hit AS string), ''),
    coalesce(cast(a.screening_only AS string), ''),
    coalesce(cast(a.well_corroborated AS string), ''),
    coalesce(cast(a.implausible AS string), ''),
    coalesce(to_json(a.citation_urls), '[]'),
    coalesce(to_json(f.source_types_arr), '[]'),
    coalesce(cast(a.n_source_urls AS string), ''),
    coalesce(a.official_website, ''),
    coalesce(cast(a.staff_present AS string), ''),
    coalesce(f.recency_of_page_update, ''),
    coalesce(f.source_content_id, ''),
    coalesce(f.source, ''),
    coalesce(cast(f.num_doctors AS string), ''),
    coalesce(cast(f.capacity_beds AS string), '')
  ), 256) AS evidence_fingerprint,
  a.tier AS heuristic_tier,
  a.score AS heuristic_score,
  a.explanation AS heuristic_explanation,
  a.evidence_json AS heuristic_evidence_json,
  a.structured_hit AS heuristic_structured_hit,
  a.claim_hit AS heuristic_claim_hit,
  a.prose_hit AS heuristic_prose_hit,
  a.screening_only AS heuristic_screening_only,
  a.well_corroborated AS heuristic_well_corroborated,
  a.implausible AS heuristic_implausible,
  a.n_source_urls,
  a.official_website,
  a.staff_present,
  f.recency_of_page_update,
  f.source,
  a.citation_urls,
  f.source_types_arr,
  to_json(a.citation_urls) AS citation_urls_json,
  to_json(f.source_types_arr) AS source_types_json,
  f.capability AS capability_raw,
  f.specialties AS specialties_raw,
  f.procedure AS procedure_raw,
  f.equipment AS equipment_raw,
  f.description AS description_raw,
  f.capability_arr,
  f.specialties_arr,
  f.procedure_arr,
  f.equipment_arr,
  f.claim_text,
  f.prose_text,
  f.full_text,
  to_json(named_struct(
    'facility', named_struct(
      'unique_id', a.unique_id,
      'name', a.name,
      'facility_type', a.facility_type,
      'operator_type', a.operator_type,
      'district_norm', a.district_norm,
      'state_name', a.state_name,
      'address_city', g.address_city,
      'pincode', g.pincode,
      'latitude', a.latitude,
      'longitude', a.longitude,
      'num_doctors', f.num_doctors,
      'capacity_beds', f.capacity_beds
    ),
    'capability', a.capability,
    'heuristic_assessment', named_struct(
      'tier', a.tier,
      'score', a.score,
      'explanation', a.explanation,
      'structured_hit', a.structured_hit,
      'claim_hit', a.claim_hit,
      'prose_hit', a.prose_hit,
      'screening_only', a.screening_only,
      'well_corroborated', a.well_corroborated,
      'implausible', a.implausible
    ),
    'source_evidence', named_struct(
      'capability_claims', f.capability_arr,
      'specialties', f.specialties_arr,
      'procedures', f.procedure_arr,
      'equipment', f.equipment_arr,
      'description', f.description,
      'claim_text', f.claim_text,
      'prose_text', f.prose_text,
      'full_text', f.full_text,
      'citation_urls', a.citation_urls,
      'source_types', f.source_types_arr,
      'n_source_urls', a.n_source_urls,
      'official_website', a.official_website,
      'staff_present', a.staff_present,
      'source_content_id', f.source_content_id
    ),
    'audit', named_struct(
      'input_snapshot_ts', cast(current_timestamp() AS string),
      'evidence_fingerprint', sha2(concat_ws('||',
        coalesce(a.unique_id, ''),
        coalesce(a.capability, ''),
        coalesce(a.name, ''),
        coalesce(a.facility_type, ''),
        coalesce(a.operator_type, ''),
        coalesce(a.district_norm, ''),
        coalesce(a.state_name, ''),
        coalesce(g.address_city, ''),
        coalesce(cast(g.pincode AS string), ''),
        coalesce(cast(a.latitude AS string), ''),
        coalesce(cast(a.longitude AS string), ''),
        coalesce(f.capability, ''),
        coalesce(f.specialties, ''),
        coalesce(f.procedure, ''),
        coalesce(f.equipment, ''),
        coalesce(f.description, ''),
        coalesce(a.tier, ''),
        coalesce(cast(a.score AS string), ''),
        coalesce(a.explanation, ''),
        coalesce(cast(a.structured_hit AS string), ''),
        coalesce(cast(a.claim_hit AS string), ''),
        coalesce(cast(a.prose_hit AS string), ''),
        coalesce(cast(a.screening_only AS string), ''),
        coalesce(cast(a.well_corroborated AS string), ''),
        coalesce(cast(a.implausible AS string), ''),
        coalesce(to_json(a.citation_urls), '[]'),
        coalesce(to_json(f.source_types_arr), '[]'),
        coalesce(cast(a.n_source_urls AS string), ''),
        coalesce(a.official_website, ''),
        coalesce(cast(a.staff_present AS string), ''),
        coalesce(f.recency_of_page_update, ''),
        coalesce(f.source_content_id, ''),
        coalesce(f.source, ''),
        coalesce(cast(f.num_doctors AS string), ''),
        coalesce(cast(f.capacity_beds AS string), '')
      ), 256)
    ),
    'notes', array(
      'Use the LLM to refine sub-signals only. The final trust tier stays deterministic.'
    )
  )) AS llm_input_json
FROM virtue_foundation_dataset_cleaned.gold.facility_capability_assessment_heuristic a
JOIN virtue_foundation_dataset_cleaned.silver.facilities_clean f
  ON a.unique_id = f.unique_id
LEFT JOIN virtue_foundation_dataset_cleaned.gold.facility_geo g
  ON a.unique_id = g.unique_id;
